export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/',
  OWNERS: '/propietarios',
  OWNER_NEW: '/propietarios/nuevo',
  OWNER_DETAIL: (id: number | string) => `/propietarios/${id}`,
  PROPERTIES: '/propiedades',
  PROPERTY_NEW: '/propiedades/nueva',
  PROPERTY_DETAIL: (id: number | string) => `/propiedades/${id}`,
  TENANTS: '/inquilinos',
  TENANT_NEW: '/inquilinos/nuevo',
  TENANT_DETAIL: (id: number | string) => `/inquilinos/${id}`,
  CONTRACTS: '/contratos',
  CONTRACT_NEW: '/contratos/nuevo',
  CONTRACT_DETAIL: (id: number | string) => `/contratos/${id}`,
  PAYMENTS: '/cobros',
  EXPENSES: '/gastos',
  SETTLEMENTS: '/liquidaciones',
  SETTLEMENT_DETAIL: (id: number | string) => `/liquidaciones/${id}`,
  RECEIPTS: '/recibos',
  REPORTS: '/reportes',
  SALES: '/ventas',
  OCCUPATIONS: '/ocupaciones',
  OCCUPATION_DETAIL: (id: number | string) => `/ocupaciones/${id}`,
  WHATSAPP_SETUP: '/configuracion/whatsapp',
} as const;
